# First, get the CSRF token
GET http://localhost:3001/api/csrf-token

###

# Then use the CSRF token in the request
POST http://localhost:3001/api/payment/nib/notify
Content-Type: application/json
Authorization: Bearer 1234567890
X-CSRF-Token: {{csrfToken}}
Cookie: csrf_token={{csrfToken}}

{
    "transactionId": "1234567890",
    "paidAmount": 100,
    "paidByNumber": "1234567890",
    "txnRef": "1234567890",
    "transactionTime": "2021-01-01T00:00:00Z",
    "accountNo": "1234567890",
    "token": "1234567890",
    "signature": "1234567890"
}
